// <auto-generated />
using System;
using BattleBunnies.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BattleBunnies.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250629160041_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BattleBunnies.Domain.Aggregates.Battle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentTurn")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Battles");
                });

            modelBuilder.Entity("BattleBunnies.Domain.Entities.Bunny", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BattleId")
                        .HasColumnType("uuid");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BattleId");

                    b.ToTable("Bunnies");
                });

            modelBuilder.Entity("BattleBunnies.Domain.Entities.Bunny", b =>
                {
                    b.HasOne("BattleBunnies.Domain.Aggregates.Battle", null)
                        .WithMany("Bunnies")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("BattleBunnies.Domain.ValueObjects.Position", "Position", b1 =>
                        {
                            b1.Property<Guid>("BunnyId")
                                .HasColumnType("uuid");

                            b1.Property<int>("X")
                                .HasColumnType("integer");

                            b1.Property<int>("Y")
                                .HasColumnType("integer");

                            b1.HasKey("BunnyId");

                            b1.ToTable("Bunnies");

                            b1.WithOwner()
                                .HasForeignKey("BunnyId");
                        });

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("BattleBunnies.Domain.Aggregates.Battle", b =>
                {
                    b.Navigation("Bunnies");
                });
#pragma warning restore 612, 618
        }
    }
}
